Activitytracker_Project/urls.py
import os

from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

import ct_projects

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^activitytracker/', include('activitytracker.urls')),
    url(r'^diplomatiki/', include('diplomatiki.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # projects
    url(r'^projects/', include('ct_projects.urls')),

    # user profile wizard
    url(r'^profile/', include('profile.urls')),

    # cloudteams terms & conditions
    url(r'^terms-and-conditions/$', ct_projects.views.terms_and_conditions, name='terms-and-conditions'),

    # home page redirect
    url(r'^$', RedirectView.as_view(url='projects/', permanent=True)),

    # media URL
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
]

profile/urls.py
from django.conf.urls import url, include
from profile import views

__author__ = 'dipap'

urlpatterns = [
    # profile
    url(r'^$', views.view_my_profile, name='view-my-profile'),
    url(r'^edit/$', views.start_wizard, name='start-profile-wizard'),

    # Brand opinions
    url(r'^get-brand-opinion$', views.get_brand_opinion, name='get-brand-opinion'),
    url(r'^opinion-about$', views.opinion_about, name='opinion-about'),

    # Notification
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/(?P<pk>\d+)/$', views.notification_view, name='notification-view'),
]

profile/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.signals import post_save

from activitytracker.models import User
from ct_projects.models import Campaign
from profile.lists import BUSINESS_SECTORS, WORK_POSITIONS, INFLUENCES, DEVICES, PLATFORMS, BRAND_OPINIONS, \
    TECH_LEVELS

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class UserProfile(models.Model):
    """
    Additional information about CloudTeams customer account
    Initially will be filled in using the wizard
    """

    # Link to user in Activity Tracker
    user = models.OneToOneField(User)

    # Avatar
    profile_picture = models.ImageField(upload_to='avatars/', blank=True, null=True, default=None)

    # Generic info
    first_name = models.CharField(max_length=255, blank=True, null=True, default=None)
    last_name_initial = models.CharField(max_length=1, blank=True, null=True, default=None)
    year_of_birth = models.IntegerField(blank=True, null=True, default=None, validators=[MinValueValidator(1930),
                                                                                         MaxValueValidator(2010)])
    # -- location is in main model -> asume it to be home location

    # Business info
    business_sector = models.CharField(max_length=127, blank=True, default='', choices=BUSINESS_SECTORS)
    work_position = models.CharField(max_length=127, blank=True, default='', choices=WORK_POSITIONS)
    work_location = models.CharField(max_length=255, blank=True, default='')
    years_experience = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(0)])

    # Tech level
    tech_level = models.CharField(max_length=31, blank=True, default='', choices=TECH_LEVELS)

    # Check if the profile wizard has run at least once
    has_been_saved = models.BooleanField(default=False, editable=False)

    def get_display_name(self):
        return '%s %s.' % (self.first_name, self.last_name_initial)

    def get_display_name(self):
        if self.first_name and self.last_name_initial:
            return '%s %s.' % (self.first_name, self.last_name_initial)
        else:
            return self.user.username

    def get_completion_progress(self):
        """
        :return: A two digit percentage ("00" - "99") indicating how much of the profile info has been completed
        """
        # TODO implement profile complete calculation logic
        points = 0

        if self.profile_picture:
            points += 5

        if self.first_name:
            points += 4

        if self.last_name_initial:
            points += 1

        if self.year_of_birth:
            points += 5

        if self.business_sector:
            points += 3

        if self.work_location:
            points += 5

        if self.years_experience:
            points += 2

        if self.tech_level:
            points += 10

        if self.user.influences.all():
            points += 15

        if self.user.devices.all():
            points += 20

        if self.user.platforms.all():
            points += 20

        if self.user.brand_opinions.all():
            points += 10

        return points

    def avatar(self):
        if not self.profile_picture:
            return None
        else:
            return '/media/avatars/' + self.profile_picture.name.split('/')[-1]


class Influence(models.Model):
    user = models.ForeignKey(User, related_name='influences')
    influence = models.CharField(max_length=255, choices=INFLUENCES)


class DeviceUsage(models.Model):
    user = models.ForeignKey(User, related_name='devices')
    device = models.CharField(max_length=255, choices=DEVICES)


class PlatformUsage(models.Model):
    user = models.ForeignKey(User, related_name='platforms')
    platform = models.CharField(max_length=255, choices=PLATFORMS)


class UserBrandOpinion(models.Model):
    user = models.ForeignKey(User, related_name='brand_opinions')
    brand = models.CharField(max_length=16)
    opinion = models.CharField(max_length=1, choices=BRAND_OPINIONS)


def on_profile_info_updated(sender, instance, created, **kwargs):
    # send campaigns
    Campaign.send_all()


# connect with update events
post_save.connect(on_profile_info_updated, sender=UserProfile)
post_save.connect(on_profile_info_updated, sender=Influence)
post_save.connect(on_profile_info_updated, sender=DeviceUsage)
post_save.connect(on_profile_info_updated, sender=PlatformUsage)
post_save.connect(on_profile_info_updated, sender=UserBrandOpinion)

profile/forms.py
from django import forms

from profile.lists import INFLUENCES, DEVICES, PLATFORMS
from profile.models import UserProfile

__author__ = 'dipap'


class UserProfileForm(forms.ModelForm):
    location = forms.CharField(required=False)
    # Influences
    influences = forms.MultipleChoiceField(choices=INFLUENCES, required=False)

    # Devices & platforms
    devices = forms.MultipleChoiceField(choices=DEVICES, required=False)
    platforms = forms.MultipleChoiceField(choices=PLATFORMS, required=False)

    class Meta:
        model = UserProfile
        exclude = ('user', 'has_been_saved',)

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        if not self.instance.first_name and self.instance.user.first_name:
            self.initial['first_name'] = self.instance.user.first_name

        if not self.instance.last_name_initial and self.instance.user.last_name:
            self.initial['last_name_initial'] = self.instance.user.last_name[0]

        if not self.instance.year_of_birth and self.instance.user.date_of_birth:
            self.initial['year_of_birth'] = self.instance.user.date_of_birth.year

        if self.instance.user.location:
            self.initial['location'] = self.instance.user.location

        self.initial['influences'] = [influence.influence for influence in self.instance.user.influences.all()]
        self.initial['platforms'] = [platform_usages.platform for platform_usages in self.instance.user.platforms.all()]
        self.initial['devices'] = [device_usage.device for device_usage in self.instance.user.devices.all()]

profile/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect

from ct_projects.models import Notification
from profile.forms import UserProfileForm
from profile.lists import DEFAULT_BRANDS, BRAND_OPINIONS
from profile.models import UserBrandOpinion, UserProfile, Influence, DeviceUsage, PlatformUsage
from profile.templatetags.profile_tags import get_brand_icon


@login_required
def view_my_profile(request):
    # load profile
    profile = request.user.profile
    params = {
        'profile': profile,
        'liked_brands': [op.brand for op in profile.user.brand_opinions.filter(opinion='P')],
        'disliked_brands': [op.brand for op in profile.user.brand_opinions.filter(opinion='N')],
    }

    if profile.has_been_saved:  # proceed to details page
        return render(request, 'profile/index.html', params)
    else:
        return redirect(reverse('start-profile-wizard'))


@login_required
def start_wizard(request):
    # initialize profile form variables
    profile = request.user.profile
    params = {
        'profile': profile,
        'profile_edit': True,
    }

    if request.method == 'GET':
        form = UserProfileForm(instance=profile)
    else:
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            # save the profile
            profile = form.save(commit=False)
            profile.has_been_saved = True
            profile.save()

            # add related information
            for influence in form.cleaned_data['influences']:
                if Influence.objects.filter(user=profile.user, influence=influence).count() == 0:
                    Influence.objects.create(user=profile.user, influence=influence)

            for influence in Influence.objects.filter(user=profile.user):
                if influence.influence not in form.cleaned_data['influences']:
                    influence.delete()

            for device in form.cleaned_data['devices']:
                if DeviceUsage.objects.filter(user=profile.user, device=device).count() == 0:
                    DeviceUsage.objects.create(user=profile.user, device=device)

            for device_usage in DeviceUsage.objects.filter(user=profile.user):
                if device_usage.device not in form.cleaned_data['devices']:
                    device_usage.delete()

            for platform in form.cleaned_data['platforms']:
                if PlatformUsage.objects.filter(user=profile.user, platform=platform).count() == 0:
                    PlatformUsage.objects.create(user=profile.user, platform=platform)

            for platform_usage in PlatformUsage.objects.filter(user=profile.user):
                if platform_usage.platform not in form.cleaned_data['platforms']:
                    platform_usage.delete()

            # update user
            profile.user.location = form.cleaned_data['location']
            profile.user.save()

            return redirect(reverse('start-profile-wizard'))

    params['form'] = form
    return render(request, 'profile/edit.html', params)


@login_required
def get_brand_opinion(request):
    # find the first brand that user has given no opinion about
    brand = None
    for b in DEFAULT_BRANDS:
        if not UserBrandOpinion.objects.filter(user=request.user, brand=b[0]):
            brand = b[0]
            break

    if not brand:
        return HttpResponse('')
    else:
        return render(request, 'profile/brand-opinion/form.html', {
            'brand': brand,
            'brand_icon': get_brand_icon(brand),
        })


def opinion_about(request):
    if request.method != 'POST':
        return HttpResponse('Only POST allowed', status=400)

    # get parameters
    brand = request.POST.get('brand', '')
    opinion = request.POST.get('opinion', '')

    # validation
    errors = []
    if brand not in [b[0] for b in DEFAULT_BRANDS]:
        errors.append('Brand must be one of %s' % ','.join([b[1] for b in DEFAULT_BRANDS]))

    if opinion not in [o[0] for o in BRAND_OPINIONS]:
        errors.append('Opinion must be one of %s' % ','.join([o[1] for o in BRAND_OPINIONS]))

    bo = UserBrandOpinion.objects.filter(user=request.user, brand=brand)
    if bo:
        bo = bo[0]
        bo.opinion = opinion
        bo.save()
    else:
        UserBrandOpinion.objects.create(user=request.user, brand=brand, opinion=opinion)

    return HttpResponse('')


@login_required
def notifications(request):
    ctx = {
        'notifications': [n for n in Notification.objects.filter(user=request.user).order_by('-created')
                          if (not n.campaign()) or (not n.campaign().has_expired())]
    }

    return render(request, 'profile/notification/all.html', ctx)


@login_required
def notification_view(request, pk):
    try:
        notification = Notification.objects.get(pk=int(pk), user=request.user)
    except Notification.DoesNotExist:
        return redirect(reverse('notifications'))
    except ValueError:
        return redirect(reverse('notifications'))

    # mark notification as seen
    notification.seen = True
    notification.save()

    return redirect(notification.url(user=request.user))

profile/templates/profile/steps/basic-info.html
<div class="container">
    <h2>Basic information</h2>

    <div class="row">
        <div class="hidden">
            {{form.profile_picture}}
        </div>

        <div class="col-xs-4">
            <div id="avatar-container">
                <div class="avatar-img" {% if p.profile_picture %}style="background-image: url(/media/{{p.profile_picture}});"{% endif %} ></div>
            </div>
            <div class="btn btn-primary" id="trigger-avatar-upload">Upload an avatar</div>
        </div>

        <div class="col-xs-8">
            <div class="row">
                <div class="col-sm-6">
                    <label for="id_first_name">Your first name</label><br />
                    {{ form.first_name }}
                </div>
                <div class="col-sm-6">
                    <label for="id_last_name_initial">The initial of your last name</label><br />
                    {{ form.last_name_initial }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label for="id_year_of_birth">Birth year</label><br />
                    {{ form.year_of_birth }}
                </div>

                <div class="col-sm-6">
                    <label for="id_location">Where do you live (only city)?</label><br />
                    {{ form.location }}
                </div>
            </div>
        </div>
    </div>
</div>

profile/templates/profile/steps/devices-and-platforms.html
<div class="container-fluid">
    <h2>Devices & platforms</h2>

    <div class="centered-fields">
        <div class="field">
            <label for="id_devices">Which of the following devices are you regularly using?</label>
            {{ form.devices }}
        </div>
        <div class="field">
            <label for="id_platforms">Choose which platforms of the following you use:</label>
            {{ form.platforms }}
        </div>
    </div>
</div>

profile/templates/profile/steps/influences.html
<div class="container-fluid">
    <h2>Influences</h2>

    <div class="centered-fields">
        <div class="field">
            <label for="id_influences">What/who of the following influence you about technology?</label>
            {{ form.influences }}
        </div>
    </div>
</div>

profile/templates/profile/steps/work.html
<div class="container-fluid">
    <h2>Your job</h2>

    <div class="centered-fields">
        <div class="field">
            <label for="id_business_sector">Choose in which business sector you're currently working</label>
            {{ form.business_sector }}
        </div>
        <div class="field">
            <label for="id_work_position">What's your position in your current work?</label>
            {{ form.work_position }}
        </div>
        <div class="field work-city">
            <label for="id_work_location">Where is your workplace (only city)?</label>
            {{ form.work_location }}
        </div>
        <div class="field">
            <label for="id_years_experience">How many years of experience do you have in this industry?</label>
            {{ form.years_experience }}
        </div>
    </div>
</div>

profile/templates/profile/steps/you-and-tech.html
<div class="container-fluid">
    <h2>You & Tech</h2>

    <div class="centered-fields">
        <div class="field">
            <label for="id_tech_level">Concerning technology, would you describe yourself as a... ?</label>
            {{ form.tech_level }}
        </div>

        {% include "profile/brand-opinion/feedback.html" %}
    </div>
</div>